project:
  type: website
  output-dir: docs
  
website:
  title: "Chase-Cote-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href:https://github.com/ctc10234-tech/Bio806-ChaseCote-LabWebsite.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Chase Cote"

format:
  html:
    theme: cerulean
    toc: true

editor: source

